In [1]:
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime

In [2]:
stock = yf.Ticker("AEO")

all_chains = [stock.option_chain(x) for x in stock.options]

In [29]:
all_calls = [x.calls for x in all_chains[:2]]
days_until_expiration = [(datetime.strptime(x, '%Y-%m-%d') - datetime.today()).days for x in stock.options[:2]]

all_calls_with_expirations = []
for c, d in zip(all_calls, days_until_expiration):
    c['daysUntilExpiration'] = d
    all_calls_with_expirations.append(c)


In [30]:
all_calls_df = pd.concat(all_calls_with_expirations)

In [31]:
print(all_calls_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 0 to 32
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   contractSymbol       60 non-null     object        
 1   lastTradeDate        60 non-null     datetime64[ns]
 2   strike               60 non-null     float64       
 3   lastPrice            60 non-null     float64       
 4   bid                  60 non-null     float64       
 5   ask                  60 non-null     float64       
 6   change               60 non-null     float64       
 7   percentChange        54 non-null     float64       
 8   volume               56 non-null     float64       
 9   openInterest         60 non-null     int64         
 10  impliedVolatility    60 non-null     float64       
 11  inTheMoney           60 non-null     bool          
 12  contractSize         60 non-null     object        
 13  currency             60 non-null     

In [32]:
import numpy as np
print(all_calls_df.impliedVolatility.shape)
z = np.tile(all_calls_df.impliedVolatility.values, (all_calls_df.impliedVolatility.shape[0], 1))
print(z)

(60,)
[[0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]
 [0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]
 [0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]
 ...
 [0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]
 [0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]
 [0.500005   0.74219008 0.62109754 ... 1.57031465 1.6406268  1.93750031]]


In [42]:
x = all_calls_df.daysUntilExpiration.values
y = all_calls_df.strike.values
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig.update_layout(title='Implied Volatility', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()


In [34]:
print(z.shape)
print(x.shape)
print(y.shape)

(60, 60)
(60,)
(60,)


In [39]:
all_calls_df[['strike', 'impliedVolatility', 'daysUntilExpiration']]


strike  impliedVolatility  daysUntilExpiration
0     20.0           0.500005                    1
1     22.5           0.742190                    1
2     23.0           0.621098                    1
3     23.5           0.660160                    1
4     24.0           0.500005                    1
5     24.5           0.519536                    1
6     25.0           0.589848                    1
7     25.5           0.601566                    1
8     26.0           0.703128                    1
9     26.5           0.812502                    1
10    27.0           0.937501                    1
11    27.5           1.078130                    1
12    28.0           1.195317                    1
13    28.5           0.937501                    1
14    29.0           1.000005                    1
15    29.5           1.718751                    1
16    30.0           1.359378                    1
17    30.5           1.914063                    1
18    31.0           1.992188                    1
19    31.5           2.304692                    1
20    32.0           2.242192                    1
21    33.0           2.625003                    1
22    34.0           2.718753                    1
23    35.0           2.867190                    1
24    36.0           3.031252                    1
25    39.0           3.468751                    1
26    40.0           3.617188                    1
0     15.0           1.421878                    8
1     20.0           0.632816                    8
2     21.0           0.746096                    8
3     22.0           0.572270                    8
4     22.5           0.486333                    8
5     23.0           0.546880                    8
6     23.5           0.496099                    8
7     24.0           0.465826                    8
8     24.5           0.494146                    8
9     25.0           0.494146                    8
10    25.5           0.523442                    8
11    26.0           0.501958                    8
12    26.5           0.523442                    8
13    27.0           0.531255                    8
14    27.5           0.550786                    8
15    28.0           0.574223                    8
16    28.5           0.640629                    8
17    29.0           0.664066                    8
18    29.5           0.718753                    8
19    30.0           0.687503                    8
20    30.5           0.734378                    8
21    31.0           0.718753                    8
22    31.5           0.820314                    8
23    32.0           0.921876                    8
24    33.0           1.039067                    8
25    34.0           1.125004                    8
26    35.0           0.875001                    8
27    36.0           1.312503                    8
28    37.0           1.000005                    8
29    38.0           1.507815                    8
30    39.0           1.570315                    8
31    40.0           1.640627                    8
32    45.0           1.937500                    8